name: Deploy to cPanel FTP

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to cPanel FTP
        uses: wzieba/Ftp-Deploy-Action@v2
        with:
          server: ftp://electronichealth.rcpandharpur.in
          username: Prashant
          password: Google@12
          local-dir: public/ftp
          remote-dir: /home/dwaz9seft2fz/public_html/electronichealth.rcpandharpur.in/Prashant
